// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navigation: string;
export const active: string;
export const icon: string;
export const line: string;
export const line2: string;
export const line1: string;
