// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const cards: string;
export const card: string;
export const text: string;
export const dateText: string;
