name: Gatsby Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: | 
          npm install
          npm run build
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths